name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-and-train:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install dvc[all] huggingface_hub

      - name: DVC pull data
        env:
          GDRIVE_TOKEN: ${{ secrets.GDRIVE_TOKEN }}
        run: |
          dvc remote modify --local gdrive_remote gdrive_use_service_account false || true
          dvc pull

      - name: Run tests
        run: pytest -q

      - name: Train (demo)
        run: python train.py --epochs 1 --out model/

      - name: Push model to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          pip install huggingface_hub
          python ci_push_to_hf.py --model-dir model/ --repo-id org-name/my-model
