name: Sync master to main
on:
  push:
    branches:
      - master # The workflow runs when changes are pushed to 'master'
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        # Checkout the main branch, which we intend to merge into
        uses: actions/checkout@v4
        with:
          ref: main # Checkout the target branch (main) first
          fetch-depth: 0 # Fetch all history for merging

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge master into main and Push
        run: |
          # Fetch the master branch from the remote
          git fetch origin master
          
          # Attempt the merge. Using --ff-only ensures it only merges 
          # if it can fast-forward, preventing merge commits and conflicts 
          # in the main branch from this action. 
          # You might want 'git merge origin/master' without --ff-only
          # if you want a merge commit every time.
          git merge origin/master --ff-only 
          
          # Check if there were changes to push (i.e., the merge succeeded)
          if [ $? -eq 0 ]; then
            echo "Merge successful, pushing to main..."
            git push origin main
          else
            echo "Merge failed (likely not a fast-forward), no push performed."
            # The workflow will still succeed if the merge isn't a fast-forward,
            # but it won't push. To fail the job on non-fast-forward,
            # remove the 'if' block and '--ff-only' and let the merge fail 
            # (it will stop on conflicts).
          fi